Application/STAS/STAS.Web/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using STAS.Services;
using STAS.Model;
using STAS.Web.Models;
using PagedList;
using System.Diagnostics;
using Microsoft.AspNetCore.Http.HttpResults;
using static NuGet.Packaging.PackagingConstants;
using System;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;
using Microsoft.IdentityModel.Tokens;

namespace STAS.Web.Controllers
{
    public class EmployeeController : Controller
    {

        private readonly EmployeeService service = new();
        private readonly ScanService scanService = new();
        private readonly ListService listService = new();

        // GET: EmployeeController
        public async Task<ActionResult> Index(int? page)
        {

            //check login
            var userName = HttpContext.Session.GetString("UserName");

            if (userName == null)
            {
                return RedirectToAction("Login", "Login");
            }

            // Create pegination consts
            const int pageSize = 8;
            int pageNumber = (page ?? 1);

            try
            {
                List<Employee> employees = await service.GetAllEmployeesAsync();
                if (employees.Count == 0)
                {
                    TempData["EmployeeEmpty"] = "You don't have employees yet.";
                }
            
                var pagedEmp = employees.Skip((pageNumber - 1) * pageSize).Take(pageSize).ToList();
                ViewBag.TotalPages = (int)Math.Ceiling((double)employees.Count / pageSize);
                ViewBag.CurrentPage = pageNumber;

                return View(pagedEmp);
            }
            catch (Exception ex)
            {
                return ShowError(ex);
            }
            
        }

        // GET: EmployeeController
        public async Task<ActionResult> Restore(int? page)
        {

            //check login
            var userName = HttpContext.Session.GetString("UserName");

            if (userName == null)
            {
                return RedirectToAction("Login", "Login");
            }

            // Create pegination consts
            const int pageSize = 8;
            int pageNumber = (page ?? 1);

            try
            {
                List<Employee> employees = await service.GetAllDeletedEmployeeAsync();

                if (employees.Count == 0)
                {
                    TempData["Error"] = "You don't have any deleted employees.";
                }

                var pagedEmp = employees.Skip((pageNumber - 1) * pageSize).Take(pageSize).ToList();
                ViewBag.TotalPages = (int)Math.Ceiling((double)employees.Count / pageSize);
                ViewBag.CurrentPage = pageNumber;

                return View(pagedEmp);
            }
            catch (Exception ex)
            {
                return ShowError(ex);
            }

        }


        // POST: EmployeeController/Restore
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Restore(int employeeId)
        {
            try
            {
                
                Employee employee = await service.SearchEmployeeByIdAsync(employeeId);

                if (!ModelState.IsValid)
                {
                    return View(employee);
                }

                employee.TypeEmployeeId = 2;
                var result = await service.RestoreEmployeeAsync(employee);

                if (result.Errors.Count != 0)
                {
                    string errorMessage = "";
                    foreach (var error in result.Errors)
                    {
                        errorMessage += error.Description + " ";
                    }
                    ViewBag.ErrorMessage = errorMessage;
                    return RedirectToAction("Restore", "Employee");
                }

                TempData["Success"] = "Employee Restored successfully.";
                return RedirectToAction("Restore", "Employee");

            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message.ToString();
                return RedirectToAction("Restore", "Employee");
            }
        }





        // GET: EmployeeController Search method
        public async Task<ActionResult> Search(string? startDate, string? endDate, int? employeeId, int? status)
        {

            //check login
            var userName = HttpContext.Session.GetString("UserName");

            if (userName == null)
            {
                return RedirectToAction("Login", "Login");
            }

            // create classes and list of employees
            EmployeeWithScans employeeWithScans = new EmployeeWithScans();
            employeeWithScans.EmployeesList = await GetEmployeeList();
            employeeWithScans.ScanTypesList = await GetTypes();
            List<ScanVM> scansVm = new List<ScanVM>();

            try
            {
                
                if (employeeId == null)
                { 
                    return View(employeeWithScans);
                }

                ViewBag.StartDate = startDate;
                ViewBag.EndDate = endDate;
                ViewBag.Status = status;
                ViewBag.EmployeeId = employeeId;

                List<ScanType> types = await listService.GetTypeScan();
                Employee employee = await service.SearchEmployeeByIdAsync((int)employeeId!);
                List<Scan> scans = await scanService.SearchScanByEmployeeIdAsync((int)employeeId);

                // search by date
                if(!String.IsNullOrEmpty(startDate) && !String.IsNullOrEmpty(endDate))
                {
                    scans = scans.Where(sc => sc.ScanDate >= Convert.ToDateTime(startDate)
                          && sc.ScanDate <= Convert.ToDateTime(endDate)).ToList();
                }
                else if (String.IsNullOrEmpty(startDate) && !String.IsNullOrEmpty(endDate))
                {
                    scans = scans.Where(sc => sc.ScanDate <= Convert.ToDateTime(endDate)).ToList();
                }
                else if (!String.IsNullOrEmpty(startDate) && String.IsNullOrEmpty(endDate))
                {
                    scans = scans.Where(sc => sc.ScanDate >= Convert.ToDateTime(startDate)).ToList();
                }

                //Filter by type
                if (status != null)
                {
                    scans = scans.Where(sc => sc.ScanType.Equals(status)).ToList();
                }

                foreach (var sc in scans)
                {
                    List<ScanType> type = types;
                    ScanVM scanVM = new ScanVM()
                    {
                        ScanId = sc.ScanId,
                        ScanDate = sc.ScanDate,
                        ScanType = type.FirstOrDefault(t => t.TypeId == sc.ScanType).TypeName
                    };

                    scansVm.Add(scanVM);
                }

                employeeWithScans.Scans = scansVm;
                employeeWithScans.Employee = employee;

                return View(employeeWithScans);
        }
            catch (Exception ex)
            {
                return ShowError(ex);
            }

        }

        // GET: EmployeeController Calculated Shifts method
        public async Task<ActionResult> Shift(string? startDate, int? employeeId)
        {

            //check login
            var userName = HttpContext.Session.GetString("UserName");

            if (userName == null)
            {
                return RedirectToAction("Login", "Login"); 
            }

            try
            {
                ViewBag.StartDate = startDate;
                ViewBag.EmployeeId = employeeId;


                ShiftVM shiftVMobject = new ShiftVM()
                {
                    EmployeesList = await GetEmployeeList(),
                    Shifts = new List<Shift>()
                };

                // Check entered data
                if (startDate == null)
                {
                    return View(shiftVMobject);
                }

                if (employeeId == null)
                {
                    return View(shiftVMobject);
                }

                //get employee and scans records
                shiftVMobject.Employee = await service.SearchEmployeeByIdAsync((int)employeeId!);
                List<Scan> scans = await scanService.SearchScanByEmployeeIdAsync((int)employeeId);

                //Calculate end date
                DateTime startDateTime = Convert.ToDateTime(startDate);
                DateTime endDateTime = startDateTime.AddDays(14);

                // filter scans by date and order it
                scans = scans.Where(sc => sc.ScanDate >= startDateTime
                          && sc.ScanDate <= endDateTime).ToList();
                scans = scans.OrderBy(s => s.ScanDate).ToList();

                //Create shift instance
                Shift currentShift = new();

                // Populate shifts

                if (scans.Count > 0) {

                    foreach (var sc in scans)
                    {
                        if (sc.ScanType == 1)
                        {
                            currentShift = new Shift
                            {
                                StartDate = sc.ScanDate,
                                EmployeeName = shiftVMobject.Employee.FullName
                            };
                        }
                        else if (sc.ScanType == 2)
                        {
                            if (currentShift == null)
                            {
                                currentShift = new Shift
                                {
                                    StartDate = startDateTime,
                                    EndDate = sc.ScanDate,
                                    EmployeeName = shiftVMobject.Employee.FullName

Application/STAS/STAS.Web/Controllers/ScanController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using STAS.Services;
using STAS.Web.Models;
using STAS.Model;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace STAS.Web.Controllers
{

    public class ScanController : Controller
    {
        private readonly EmployeeService empService = new();
        private readonly ScanService scanService = new();
        private readonly ListService listService = new();


        // GET: ScanController
        //public ActionResult Index()
        //{
        //    return View();
        //}

        // GET: ScanController/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        // GET: ScanController/Create
        public async Task<ActionResult> Create(int? id)
        {

            //check login
            var userName = HttpContext.Session.GetString("UserName");

            if (userName == null)
            {
                return RedirectToAction("Login", "Login");
            }

            ScanAddEditVM scanVM = new();
            try
            {
                if (id == null) new Exception("No parameter in the request");

                
                Employee employee = await empService.SearchEmployeeByIdAsync((int)id);

                if (employee == null) new Exception("Wrong employee id in the request");

                scanVM.scan.ScanDate = DateTime.Now;
                scanVM.scan.EmployeeId = (int)id;
                scanVM.EmployeeName = employee!.FullName;
                scanVM.ScanTypesList = await GetTypes();

                return View(scanVM);

            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message.ToString();
                return RedirectToAction("Details", "Employee", new { id = scanVM.scan.EmployeeId });
            }
        }

        // POST: ScanController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ScanAddEditVM scanVM)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    scanVM.ScanTypesList = await GetTypes();
                    return View(scanVM);
                }

                Scan scan = new Scan
                {
                    ScanDate = scanVM.scan.ScanDate,
                    EmployeeId = scanVM.scan.EmployeeId,
                    ScanType = scanVM.scan.ScanType
                };


                var result = await scanService.AddScanRecordAsync(scan);

                if (result.Errors.Count != 0)
                {
                    string errorMessage = "";
                    foreach (var error in result.Errors)
                    {
                        errorMessage += error.Description + " ";
                    }
                    ViewBag.ErrorMessage = errorMessage;
                    return View(scan);
                }

                TempData["Success"] = "Scan created successfully.";
                return RedirectToAction("Details", "Employee", new { id = scan.EmployeeId });

            }
            catch(Exception ex)
            {
                TempData["Error"] = ex.Message.ToString();
                return RedirectToAction("Details", "Employee", new { id = scanVM.scan.EmployeeId });
            }
        }

        // GET: ScanController/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            //check login
            var userName = HttpContext.Session.GetString("UserName");

            if (userName == null)
            {
                return RedirectToAction("Login", "Login");
            }

            Scan scan = new();
            try
            {
                if (id == null) new Exception("No parameter in the request");

                ScanAddEditVM scanVM = new();
                scan = await scanService.GetScanByIdAsync((int)id!);

                if (scan == null) new Exception("Wrong parameter in the request");

                scanVM.scan.ScanId = scan!.ScanId;
                scanVM.scan.ScanDate = scan.ScanDate;
                scanVM.scan.EmployeeId = scan.EmployeeId;
                Employee emp = await empService.SearchEmployeeByIdAsync(scan.EmployeeId);
                scanVM.EmployeeName = emp.FullName;
                scanVM.scan.ScanType = scan.ScanType;
                scanVM.scan.RecordVersion = scan.RecordVersion;
                
                scanVM.ScanTypesList = await GetTypes();

                return View(scanVM);

            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message.ToString();
                return RedirectToAction("Details", "Employee", new { id = scan.EmployeeId });
            }
        }

        // POST: ScanController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ScanAddEditVM scanVM)
        {
            try
            {

                if (!ModelState.IsValid)
                {
                    return View(scanVM);
                }

                Scan scan = new Scan
                {
                    
                    ScanId = scanVM.scan.ScanId,
                    ScanDate = scanVM.scan.ScanDate,
                    EmployeeId = scanVM.scan.EmployeeId,
                    ScanType = scanVM.scan.ScanType,
                    RecordVersion = scanVM.scan.RecordVersion
                    
                };


                var result = await scanService.UpdateRecordAsync(scan);

                if (result.Errors.Count != 0)
                {
                    string errorMessage = "";
                    foreach (var error in result.Errors)
                    {
                        errorMessage += error.Description + " ";
                    }
                    ViewBag.ErrorMessage = errorMessage;
                    return View(scan);
                }

                TempData["Success"] = "Scan created successfully.";
                return RedirectToAction("Details", "Employee", new { id = scan.EmployeeId });


            }
            catch(Exception ex) 
            {
                TempData["Error"] = ex.Message.ToString();
                return RedirectToAction("Details", "Employee", new { id = scanVM.scan.EmployeeId });
            }
        }


        #region Private Methods


        private ActionResult ShowError(Exception ex)
        {
            return View("Error", new ErrorViewModel
            {
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier,
                Exception = ex
            });
        }

        private async Task<IEnumerable<SelectListItem>>? GetTypes()
        {
            var types = await new ListService().GetTypeScan();

            return types.Select(t =>
            new SelectListItem
            {
                Value = t.TypeId.ToString(),
                Text = t.TypeName
            }).ToList();
        }


        #endregion
    }
}

Application/STAS/STAS.Web/Views/Employee/Create.cshtml
@model STAS.Model.Employee

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">


            <div class="row justify-content-center" id="errorMessageRow">
                @if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
                {
                    <div class="col-6">
                        <div class="alert alert-danger " role="alert" id="errorMessageContainer">
                            @ViewBag.ErrorMessage
                        </div>
                    </div>
                }

            </div>

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="EmployeeId" class="form-control" type="hidden" />
            <input asp-for="TypeEmployeeId" class="form-control" type="hidden"/>
            <input asp-for="RecordVersion" class="form-control" type="hidden" />
            <div class="form-group">
                <label asp-for="EmployeeNumber" class="control-label"></label>
                <input asp-for="EmployeeNumber" class="form-control" />
                <span asp-validation-for="EmployeeNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MiddleInitial" class="control-label"></label>
                <input asp-for="MiddleInitial" class="form-control" />
                <span asp-validation-for="MiddleInitial" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group pt-4">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a class="btn btn-info" asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Application/STAS/STAS.Web/Views/Employee/Details.cshtml
@model STAS.Web.Models.EmployeeWithScans
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor


@{
    ViewData["Title"] = "Details";
    var userRole = HttpContextAccessor.HttpContext.Session.GetString("Role");
    bool isAdmin = (userRole == "Administrator");
}

<div class="col-md-12">
    @if (TempData["Error"] != null)
    {
        <div class="alert alert-danger text-center">
            @TempData["Error"]
        </div>
    }
</div>


<div class="col-md-12">
    @if (TempData["Success"] != null)
    {
        <div class="alert alert-success text-center">
            @TempData["Success"]
        </div>
    }
</div>

<h1>Employee Details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.EmployeeId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Employee.EmployeeId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.EmployeeNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Employee.EmployeeNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Employee.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.MiddleInitial)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Employee.MiddleInitial)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Employee.LastName)
        </dd>
    </dl>
</div>


    @if (Model.Scans!.Count == 0)
    {
        <h4 class="text-center text-warning">This employee does not have scans.</h4>
    }

<div class="col-md-12">
    <div style="max-height: 350px; overflow-y: auto;">

    @if (Model.Scans!.Count != 0)
    {
    <table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Scans![0].ScanId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Scans![0].ScanDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Scans![0].ScanType)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Scans)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ScanId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ScanDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ScanType)
                </td>
                @if (isAdmin)
                {
                <td>
                    <div style="display: flex; gap: 5px;">
                        <div class="btn btn-warning">@Html.ActionLink("Edit", "Edit", "Scan", new { id = item.ScanId }, new { style = "text-decoration: none;" })</div>
                    </div>
                </td>
                }
            </tr>
        }
        </tbody>
    </table>
    }
    </div>
</div>

<div class="pt-4">
    @if (isAdmin)
     {
        @Html.ActionLink("Create Scan", "Create", "Scan", new { id = Model.Employee.EmployeeId }, new { @class = "btn btn-success", style = "text-decoration: none;" })
        @Html.ActionLink("Edit", "Edit", new { id = Model.Employee.EmployeeId }, new { @class = "btn btn-warning", style = "text-decoration: none;" })
     }
    <a class="btn btn-info" asp-action="Index">Back to List</a>
</div>

Application/STAS/STAS.Web/Views/Employee/Restore.cshtml
@model IEnumerable<STAS.Model.Employee>

@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@{
    ViewData["Title"] = "Restore Employees List";
    var userRole = HttpContextAccessor.HttpContext.Session.GetString("Role");
    bool isAdmin = (userRole == "Administrator");
}

<div class="col-md-12">
    @if (TempData["Error"] != null)
    {
        <div class="alert alert-danger text-center">
            @TempData["Error"]
        </div>
    }
</div>


<div class="col-md-12">
    @if (TempData["Success"] != null)
    {
        <div class="alert alert-success text-center">
            @TempData["Success"]
        </div>
    }
</div>


<h1>Restore</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.EmployeeId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmployeeNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EmployeeId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmployeeNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                    <form action="Restore" method="post" >
                        @Html.AntiForgeryToken()
                        <input type="hidden"  name="EmployeeId" value="@item.EmployeeId" />
                        <input type="submit" value="Restore" class="btn btn-primary" />
                    </form>
            </td>
        </tr>
}
    </tbody>
</table>

Application/STAS/STAS.Web/Views/Employee/Search.cshtml
@model STAS.Web.Models.EmployeeWithScans
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor


@{
    ViewData["Title"] = "Search";
    var userRole = HttpContextAccessor.HttpContext.Session.GetString("Role");
    bool isAdmin = (userRole == "Administrator");
}

<h2 class="pb-5">Search Page</h2>

<div class="col-md-12">
    @if (TempData["Error"] != null)
    {
        <div class="alert alert-danger text-center">
            @TempData["Error"]
        </div>
    }
</div>


<div class="col-md-12">
    @if (TempData["Success"] != null)
    {
        <div class="alert alert-success text-center">
            @TempData["Success"]
        </div>
    }
</div>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Search">
            <div>
                <dl class="dl-horizontal">
                    <dt>
                        <label>Start Date</label>
                    </dt>
                    <dd>
                        <input name="StartDate" value="@ViewBag.StartDate" class="form-control" type="date" />
                    </dd>
                    <dt>
                        <label>End Date Date</label>
                    </dt>
                    <dd>
                        <input name="EndDate" value="@ViewBag.EndDate" class="form-control" type="date" />
                    </dd>
                    <dt>
                        <label>Employee Full Name</label>
                    </dt>
                    <dd>
                        <select name="employeeId" asp-items="Model.EmployeesList" class="form-select">
                            <option value="">---Select Employee---</option>
                        </select>
                    </dd>
                    <dt>
                        <label>Scan Status</label>
                    </dt>
                    <dd>
                        <select name="status" asp-items="Model.ScanTypesList" class="form-select">
                            <option>---Select Type---</option>
                        </select>
                    </dd>
                    <dd>
                        <span class="list-group-numbered" id="basic-text1">
                            <button type="submit" class="btn btn-primary">Search</button>
                            <button type="reset" class="btn btn-primary">Reset</button>
                        </span>
                    </dd>
                </dl>
            </div>
        </form>

        <div>
            <dl class="row">
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.Employee.EmployeeId)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.Employee.EmployeeId)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.Employee.EmployeeNumber)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.Employee.EmployeeNumber)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.Employee.FirstName)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.Employee.FirstName)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.Employee.MiddleInitial)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.Employee.MiddleInitial)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.Employee.LastName)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.Employee.LastName)
                </dd>
            </dl>
        </div>
    </div>

    <div class="col-md-8">
    @if (Model.Scans == null || Model.Scans!.Count == 0)
    {
        <h4 class="text-center text-warning">This search does not have results.</h4>
    }
    else
    {
        <div class="col-md-12">
            <div style="max-height: 350px; overflow-y: auto;">

                @if (Model.Scans!.Count != 0)
                {
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Scans![0].ScanId)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Scans![0].ScanDate)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Scans![0].ScanType)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Scans)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ScanId)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ScanDate)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ScanType)
                                    </td>
                                        @if (isAdmin)
                                        {
                                        <td>
                                            <div style="display: flex; gap: 5px;">
                                                <div class="btn btn-warning">@Html.ActionLink("Edit", "Edit", "Scan", new { id = item.ScanId }, new { style = "text-decoration: none;" })</div>
                                            </div>
                                        </td>
                                        }
                                </tr>
                            }
                        </tbody>
                    </table>
                }
            </div>
        </div>
    }
    </div>   
</div>
       